documented code
Yggdrasil-World/DAL pull request #8
Opened 2024-02-25 16:44 UTC by Invincible2211

closes #7

2024-02-27 16:53 UTC, Morazzer requested changes
You might also want to extract common methods to a either interface with a default implementation or to a Utility class

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/datasources/ConfigDB.java
>  public class ConfigDB implements DataSource<String> {
Maybe rename it to `ConfigDS` or `ConfigDataSource` as it's not really a data base?

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/datasources/RabbitMQ.java
> +     * It is used to handle incoming messages from RabbitMQ.
```suggestion
     * used to handle incoming messages from RabbitMQ.
```
The description of the field modifiers aswell as the description of the type is unnecessary.

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/datasources/RabbitMQ.java
> +     * The RabbitMQ constructor creates a RabbitMQ object with the specified queue name.
```suggestion
     * Creates a RabbitMQ object with the specified queue name.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/DALDefaultEventBus.java
>  public class DALDefaultEventBus implements DALEventbus{
Either change it to `DALDefaultEventbus` or change the `DALEventbus` to match this, don't mix upper and lower case.

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/DALDefaultEventBus.java
> +     */
You don't necessarily have to have these comments here as they are already present in the super type.

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/DALDefaultEventBus.java
> +     */
Same as above.

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/DALEventbus.java
>      boolean triggerEvent(DataSourceDataEvent event);
Personally i think the term `fire` is better for events but it's up to you to decide

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/DataSourceDataListener.java
>          return (Class<T>) ((ParameterizedType) getClass().getGenericInterfaces()[0])
Again might cause problems with raw types

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/events/RabbitMQDataReceivedEvent.java
> + * It implements the DataReceivedEvent interface.
Not required to say this, as it's obvious when looking at the class

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/events/RabbitMQDataReceivedEvent.java
> +     * This event contains the data source from which the data is received and the RabbitMQ message that contains the received data.
This is just a repetition of the documentation that is already present above the class

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/events/RabbitMQDataReceivedEvent.java
> +     * Retrieves the data source of the RabbitMQDataReceivedEvent.
```suggestion
     * Retrieves the data source of the Event.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/events/RabbitMQDataReceivedEvent.java
> +     * Retrieves the RabbitMQ message associated with the event.
```suggestion
     * Retrieves the RabbitMQ message associated with the Event.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/event/listeners/DataReceivedListener.java
> + * T must be a subclass of DataSourceDataEvent.
Not required to say as again it's obvious when looking at the interface

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/network/rabbitmq/RabbitMQMessage.java
> + * The RabbitMQMessage class represents a message in RabbitMQ.
Im not sure if the `in` fits in this sentence

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/network/rabbitmq/RabbitMQPackage.java
> + * A RabbitMQPackage consists of a header and data.
```suggestion
 * Implementation of the Package interface for RabbitMQ.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/network/rabbitmq/RabbitMQPackage.java
> +     * A RabbitMQPackage consists of a header and data.
Just a repetition of the class level documentation

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/data/network/rabbitmq/RabbitMQPackage.java
> +     * Converts the RabbitMQPackage object to a byte array.
```suggestion
     * Converts the Package object to a byte array.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/exceptions/DuplicateAdapterForClassException.java
> + * Exception thrown when attempting to add a duplicate adapter for a class in the AdapterLibrary.
```suggestion
 * Exception for attempting to add a duplicate adapter for a class in the AdapterLibrary.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/exceptions/MissingPipelineException.java
> + * This class represents an exception that is thrown when there is no pipeline available for a request.
```suggestion
 * Exception for when there is no pipeline available for a request.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/DALPipeline.java
> + * or writing data from/to a data source.
```suggestion
 * or writing data from or to a data source.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/DALPipeline.java
> + * that are assignable from Pipeline.
This is wrong the `ClassCollector` does implement this behavior, not the interface.

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/DALPipeline.java
> + * public interface Pipeline { }
This isn't really an example usage

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/DALPipelineProzessor.java
> + * The DALPipelineProzessor class represents a processor for data access layer (DAL) pipelines.
```suggestion
 * The DALPipelineProzessor class represents a processor for DAL pipelines.
```
At this point you shouldn't have to explain what the abbreviation means.

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/DALPipelineProzessor.java
> +     * It adds the ClassCollector instance to the pipeline collection.
You are repeating yourself here

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/Pipeline.java
> + * The Pipeline interface represents a pipeline for reading or writing data from/to a data source.
```suggestion
 * The Pipeline interface represents a pipeline for reading or writing data from or to a data source.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/PipelineCollector.java
> + * The PipelineCollector interface is responsible for collecting classes that are annotated with the `DALPipeline` annotation and are assignable from the `Pipeline` class.
This behavior isn't implemented by the interface

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/PipelineCollector.java
> +     * @return a set of classes that implement the {@code Pipeline} interface
Again this behavior is only present in the implementation, but not in the interface

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/pipeline/implementations/DefaultConfigPipeline.java
> + * It implements the ReadPipeline interface for reading data and the WritePipeline interface for writing data.
This seems rather unnecessary as it's obvious when looking at the class hierarchy

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/requests/DALReadRequest.java
> + * It extends the DALRequest interface.
Again seems unnecessary to mention as it's obvious

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/requests/DALReadRequest.java
>          return (Class<T>) ((ParameterizedType) getClass().getGenericInterfaces()[0])
Again might cause problems with raw usage

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/requests/DALRequest.java
> + * This interface represents a data access layer (DAL) request.
Again you shouldn't have to explain the abbreviation of the name

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/requests/DALWriteRequest.java
> + * It extends the DALRequest interface.
Again seems unnecassary as it's obvious

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/requests/DALWriteRequest.java
>          return (Class<T>) ((ParameterizedType) getClass().getGenericInterfaces()[0])
Again might cause problems with raw usage

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/requests/implementations/ConfigReadRequest.java
> + * It implements the {@code DALReadRequest} interface with {@code ConfigDB} as the data source type.
This is unnecassary to mention as again it's obvious

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/requests/implementations/ConfigWriteRequest.java
> + * It implements the `DALWriteRequest` interface with `ConfigDB` as the data source type and `String` as the data type being written.
This is unnecassary to mention as again it's obvious

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/responses/DALResponse.java
> + * The DALResponse interface represents a response from the DAL (Data Access Layer) containing data of type T.
You don't have to explain the abbreviation

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/responses/implementations/ConfigResponse.java
> + * The ConfigResponse class represents a response from the DAL (Data Access Layer) that contains configuration data of type String.
You don't have to explain the abbreviation

Also i don't think that the meaning of the sentence is clear here, maybe rephrase it

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/responses/implementations/ConfigResponse.java
> + * It implements the DALResponse interface with String as the type parameter.
Also this is unnecessary to mention as it's obvious

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/strings/DatabaseStrings.java
>  public interface DatabaseStrings {
Maybe rename to `DatabaseConstants`?

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/strings/logging/AdapterLibraryLogger.java
> + * The AdapterLibraryLogger interface provides constants for logging messages related to AdapterLibrary.
```suggestion
 * The AdapterLibraryLogger provides constants for logging messages related to the AdapterLibrary.
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/strings/logging/DALLogger.java
> + * DALLogger is an interface that provides constants for logging messages related to the DAL (Data Access Layer) operations.
```suggestion
 * DALLogger provides constants for logging messages related to the DAL operations.
```
again no need to explain the abbreviation

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/strings/logging/DALLogger.java
> + * - DAL_EXCEPTION_PIPELINE: A log message indicating that no pipeline is configured for a request, with a placeholder for the request class name.
Maybe explain these documentations at field level and not at class level?

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/strings/logging/DALPipelineProzessorLogger.java
>  public interface DALPipelineProzessorLogger {
```suggestion
public interface DALPipelineProzessorLoggerMessages {
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/strings/logging/DatasourceLibraryLogger.java
>  public interface DatasourceLibraryLogger {
```suggestion
public interface DatasourceLibraryLoggerMessages {
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/utils/ByteUtils.java
>  public class ByteUtils {
```suggestion
public class ByteArrayUtils {
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/utils/ByteUtils.java
>          byte[] result = new byte[arrayA.length+arrayB.length];
Maybe use the following code instead.
```java
    byte[] newArray = Arrays.copyOf(arrayA, arrayA.length + arrayB.length);
    System.arraycopy(arrayB, 0, newArray, arrayA.length, arrayB.length);
    return newArray;
```

2024-02-27 16:53 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/utils/ClassCollector.java
> + * It implements default implementations for the AdapterCollector, PipelineCollector, and DatasourceCollector interfaces.
this is a rather weird sentence as you are saying the same thing twice.

2024-02-27 16:55 UTC, Morazzer commented
Also you could have used a [ci skip tag](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) for this pr, but that is just a side note.

2024-02-29 11:35 UTC, Invincible2211 commented on src/main/java/de/yggdrasil/core/dal/utils/ClassCollector.java
> + * It implements default implementations for the AdapterCollector, PipelineCollector, and DatasourceCollector interfaces.
naja, es gibt ja die allgemeine Funktion ( collect(...) ) und die spezifischen Interface implementations, also ist imo nicht gedoppelt

2024-02-29 14:02 UTC, Morazzer approved these changes

2024-02-29 14:03 UTC, merged